### ISSUE TITLE
为什么删除了

### ISSUE THREAD

**Issue by sinary-sys** [ygowill/uestc_graduate_syllabus#1]

**Comment by ygowill** [comment]
看了一下是因为当时用来生成ics的外部js是混淆过的，不符合greasyfork的规则，被人举报了。。临时的解决方案是，你可以直接在tempermonkey里新建一个用户脚本，复制粘贴这个文件里的内容[ics_generation.js](https://github.com/ygowill/uestc_graduate_syllabus/blob/main/ics_generation.js)，后面有空我会修一下greasyfork上的内容。。。

**Comment by ygowill** [comment]
已修复
