### ISSUE TITLE
你好，为什么下载系统中的2022年的课表，在手机中显示是2021年的日程

### ISSUE THREAD

**Issue by clear-all** [ygowill/uestc_graduate_syllabus#2]
油猴脚本确实很方便导出课表，但是今天晚上使用过程中，导入手机发现时间全变成了去年的了

**Comment by ygowill** [comment]
因为这个脚本需要获取开学第一周周一的日期，但是我不知道有什么办法获取，于是去年写的时候硬编码了。。。今年忘记更新这个脚本了。。现在已经修复了，你更新一下tampermonkey的脚本，重新获取一下吧。。

**Comment by clear-all** [comment]
大佬牛逼，搞定了，感谢！！！
